### ISSUE TITLE
Is it possible to access the sync-gateway admin interface from the container? 

### ISSUE THREAD

**Issue by cue232s** [couchbase/docker#110]

**Comment by tleyden** [comment]
You have two options:

- Change the config to bind to 0.0.0.0:4985 (all interfaces), and then you can do a port mapping from the host to the container, and access it from the host.  Be careful with this, since port 4985 should never be exposed publicly, and you don't want to create a security hole.

- Use `docker exec` to get a "shell" inside the container, and then access `http://localhost:4985`

Also, the [forums](http://forums.couchbase.com) are a better place to ask questions, this issue tracker is meant to be for bugs.
