### ISSUE TITLE
Windows DockerFile for community edition

### ISSUE THREAD

**Issue by mail2hjain** [couchbase/docker#147]
@Couchbase Community : Do we have plans to also provide windows DockerFile for the community edition? 
Any hints to get started in this direction is also much appreciated. TIA.

**Comment by ceejatec** [comment]
At this time, no, we have no plans to support Windows Docker. I did do some experiments in the very early days of Windows Docker, and was able to get something more or less working then, but I know things have changed significantly since that time. However, the Couchbase .msi installer is pretty straightforward, so I can't imagine it would be unusually difficult. Just be aware that the installer creates and starts a Windows Service, so you would need to do whatever is the Docker best practice for services - I feel sure such a best practice exists.

**Comment by mail2hjain** [comment]
Appreciate the prompt reply. I will do some experiments on this. Thanks.
