### ISSUE TITLE
dockerfile config changes

### ISSUE THREAD

**Issue by Srinivasa381224** [couchbase/docker#148]
Hi, am srinivasa working as a devops engineer am created simple docker file for my application i need to change some configuration of that application through dockerfile is there any way to change after war file is generated help me for this

**Comment by ceejatec** [comment]
This repository is strictly for the Dockerfiles for products provided by Couchbase, none of which are Java-based, so this isn't a good place to ask your question. Briefly, though, one possible solution would be to write a shell script which starts up your Java server in the background, and then does whatever command line steps are necessary to configure the running server. You would then COPY the shell script into your Docker image, and use the ENTRYPOINT Dockerfile directive to tell Docker to run that script when creating a new container. If you do this, make sure the last command in the shell script is "wait" so that the shell script won't immediately exit after doing the configuration steps (or else the container will immediately terminate).
