### ISSUE TITLE
Deploying to a swarm

### ISSUE THREAD

**Issue by jnordberg** [couchbase/docker#161]
I'm trying to deploy a couchbase cluster to a docker swarm and want nodes to communicate over a overlay network but I'm not sure how to configure the nodes to find eachother since couchbase setup won't let me assign a hostname.

How can I get nodes to find eachother without static ip addresses?

Refs #82

**Comment by jnordberg** [comment]
I guess another way to ask this question is: Are nodes still keyed by their IP? Because if that's the case it's not possible to run a cluster in docker let alone using a swarm.

The official instructions found [here](https://docs.couchbase.com/server/current/install/getting-started-docker.html#multi-node-cluster-many-hosts) will result in a cluster that is broken if any container is restarted.

**Comment by ceejatec** [comment]
The official instructions for "Multi-Node Cluster with Each Container on Its Own Host" work fine, and is the only method currently supported for multi-node clusters in Docker. We also have the Cloud Native Database product which includes an Autonomous Operator for managing deployments in Kubernetes, OpenShift, Amazon EKS, Google GKE, and Microsoft AKS: https://docs.couchbase.com/operator/current/overview.html .

With that said, let's talk about your questions. When configuring Server and adding nodes, you can specify a fully-qualified domain name instead of an IP. So if you can arrange for DNS to resolve to the correct internal IPs of your containers, things seem to work. I have mocked up a scenario using Swarm like this:

```version: '3.8'

services:
  node1:
    image: couchbase/server:7.0.0
    networks:
      - cluster-network
    ports:
      - target: 8091
        published: 8091
        protocol: tcp
        mode: host
    volumes:
      - "/tmp/node1:/opt/couchbase/var"
    deploy:
      endpoint_mode: dnsrr
  node2:
    image: couchbase/server:7.0.0
    networks:
      - cluster-network
    volumes:
      - "/tmp/node2:/opt/couchbase/var"
    deploy:
      endpoint_mode: dnsrr
  node3:
    image: couchbase/server:7.0.0
    networks:
      - cluster-network
    volumes:
      - "/tmp/node3:/opt/couchbase/var"
    deploy:
      endpoint_mode: dnsrr

networks:
  cluster-network:
    name: internal
```

Explanations:
1. Normal Docker service-discovery DNS will allow the service name to resolve, so eg. "node2" will resolve to an IP in the above containers. However Couchbase does require a fully-qualified domain name containing at least one dot. By putting `name: internal` on the network as shown, Docker's DNS will also resolve eg. "node2.internal" to the container's IP.
2. The default Docker DNS endpoint mode "vip" creates "phantom" IP addresses and routes them to the containers' real IPs; it's doing some form of masquerading. In that case, "node1.internal" might resolve to 10.0.18.7 where the container's actual IP address is 10.0.18.8. This doesn't work for Couchbase; it is necessary that the DNS name given must both be accessible to the originating server AND resolve to an IP that the target server can bind to. By specifying the endpoint mode "dnsrr" instead, the Docker DNS server will resolve names to the actual container IPs.
3. The dnsrr endpoint mode is incompatible with the default "ingress" mode for exposing ports. To expose port 8091 from node1, we have to use "host" mode.
4. The volume mount for `/opt/couchbase/var` allows Couchbase's data to persist outside the container.

At any rate, with all the above, you can deploy the swarm with `docker stack deploy -c stackfile.yaml couchbase` to create a stack named "couchbase". Then, visit http://127.0.0.1:8091/ in your browser; configure the initial node with the name "node1.internal" in the setup wizard; and then use Add Server to add "node2.internal" and "node3.internal" to the cluster and rebalance.

You can now kill one of the nodes with `docker service scale couchbase_node2=0` and see that it goes red in the UI. Finally, `docker service scale couchbase_node2=1` will create a new container - with a new IP address - and that container will seamlessly rejoin the cluster.

This is obviously a toy example. I had to pull a lot of stupid Docker tricks to make its DNS server work the way Couchbase wants it to, and clearly there's no true scaling possible here; if you scale one of those nodes up to 2 it will certainly not work. But it does demonstrate that - so long as you can use DNS in a way that Couchbase likes - you are NOT required to using IP addresses, and that you can replace one Docker container with another one and still maintain a cluster.

I can envision a more complex scenario where you use some kind of external service-discovery DNS, such as Consul, that would provide fully-qualified domain names dynamically based on Swarm node names and IDs. Along with that, you could have a customized entrypoint script in your Couchbase Docker image which can discover the cluster and add itself to it using `couchbase-cli`. That could allow seamless scale up, at least. You would need to handle other lifecycle events too, like a node dropping out the cluster when the stack is scaled down. It's a non-trivial problem, and at the end of it I think you would have re-implemented our Autonomous Operator.

**Comment by jnordberg** [comment]
Thank you so much for that detailed response! Setting `endpoint_mode: dnsrr` and having dots in the hostnames (adding a named alias to the network worked as well, example below) got me up and running! I will link this issue on stack overflow where I saw people asking similar questions.

```yaml
services:
  node1:
    image: couchbase:community
    networks:
      couchbase:
        aliases:
          - node1.swarm
    deploy:
      endpoint_mode: dnsrr
 ```

I agree with you that auto-scaling is a different beast but I wouldn't call a swarm setup without it a toy :) There is benefits to being able to manage a cb cluster using swarm, easy to keep the database roped off and give access to apps that need it, can move stuff around between servers, effortless updates etc.

**Comment by ceejatec** [comment]
Glad it was helpful! Thank you for sharing it on stackoverflow as well.

May I close this issue?

**Comment by jnordberg** [comment]
You may not 😛
