### ISSUE TITLE
Publish aarch64 couchbase images

### ISSUE THREAD

**Issue by yogurtearl** [couchbase/docker#175]
[Looks like couchbase has ARM support](https://issues.couchbase.com/browse/MB-42239), but I don't see any aarch64 docker images published: 
https://hub.docker.com/_/couchbase

Please publish  aarch64 couchbase images. 

Please test them on AWS ARM support and on docker running on macOS Apple silicon.

**Comment by ceejatec** [comment]
Couchbase Server with Linux aarch64 support is not GA yet although it is coming soon. That will include Docker support. Those images have been tested in AWS and on M1 Macs.

It is likely that initially the aarch64 image will only be available on the Docker image "couchbase/server", not the Official Docker image "couchbase", due to a limitation required by the Docker Official Image program (https://github.com/docker-library/official-images/pull/11752#issuecomment-1029482689 ). The couchbase/server images are built by us from the same Dockerfile as the official image, though, and are equally supported for all uses.

**Comment by MikeGoldsmith** [comment]
When do you expect to publish the new docker images to [couchbase/server](https://hub.docker.com/u/couchbase/server)?

**Comment by ceejatec** [comment]
They went up last week, in fact; official GA date for Couchbase Server 7.1.0 was Monday May 10. The images are:

couchbase/server:7.1.0-aarch64 (Enterprise Edition)
couchbase/server:community-7.1.0-aarch64 (Community Edition)

**Comment by MikeGoldsmith** [comment]
Interesting, dockerhub doesn't list them. I've done a manual `docker pull couchbase/server:7.1.0-aarch64` and it found it.

Thanks @ceejatec 👍🏻

**Comment by MikeGoldsmith** [comment]
Oh, actually dockerhub does. The issue is that all tags are republished.

Is it intentional to republish tags so often?

For example, the default view with Newest and no filter shows these tags published only two days ago:
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/3481731/168296684-07793b39-6a48-4ff7-b8ca-2f7194a0e989.png">

**Comment by ceejatec** [comment]
Yes, we frequently re-publish images when the base image is updated for security fixes. It is a little annoying that Docker Hub sorts by date rather than version, although I guess I can understand why. I've had similar problems finding things on other images for this reason.

**Comment by ade-verd** [comment]
Hi, 
I did not find any aarch64 image for Couchbase Server 7.0.3 (Enterprise Edition).

Do you plan to publish an aarch64 image for this version ?

**Comment by ceejatec** [comment]
@MikeGoldsmith FYI, Couchbase Server 7.1.1 was released this week, and we now have proper multi-arch Docker image support: couchbase/server:7.1.1 and couchbase/server:7.1.1-community work for both x86_64 and aarch64. Also, the Official image couchbase:7.1.1 and couchbase:7.1.1-community will likewise be multi-arch once it is approved and published by Docker (probably within the next 24 hours).

**Comment by MikeGoldsmith** [comment]
Great, thanks for the update @ceejatec 👍🏻

**Comment by rochdev** [comment]
I don't see support for `linux/arm64` in `couchbase/server-sandbox`. Was the change only done for the production server?
