### ISSUE TITLE
how to create a default bucket?

### ISSUE THREAD

**Issue by ChopperLee2011** [couchbase/docker#21]
i add create bucket command under running this docker, but not work;
`docker run -d -p 8091:8091 $COUCHBASE

/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 -u Administrator -p password \
       --bucket=test_bucket \
       --bucket-type=couchbase \
       --bucket-port=11222 \
       --bucket-ramsize=200 \
       --bucket-replica=1
`
anyone know how to handle it?

**Comment by ceejatec** [comment]
Did you run the second command (/opt/couchbase/bin/couchbase-cli) from outside the Docker container, or had you used something like "docker exec" to enter it?

What error / problem did you have when running?

**Comment by ChopperLee2011** [comment]
sorry, i should run bucket-create include a `docker run` command.

**Comment by ceejatec** [comment]
Yes, because /opt/couchbase/bin/couchbase-cli doesn't exist on your system (unless you've also installed Couchbase there). You need to run it in a container, eg:

docker run couchbase/server couchbase-cli --bucket=test_bucket \
--bucket-type=couchbase \
--bucket-port=11222 \
--bucket-ramsize=200 \
--bucket-replica=1

**Comment by tleyden** [comment]
Closing as I don't see any action items here.
