### ISSUE TITLE
Create branches, not directories

### ISSUE THREAD

**Issue by abhijitsarkar** [couchbase/docker#56]
I'd like to suggest that you create branches for new releases instead of creating [directories](https://github.com/couchbase/docker/tree/master/enterprise/couchbase-server), so that whoever interested can easily do a compare and see the differences.

**Comment by tleyden** [comment]
Interesting suggestion!  Currently you can compare by cloning the repo and running `diff` on the command line.

I definitely agree things are a bit wonky/clunky as they stand though.  Will keep the branching idea in mind, and try to find out what other projects are doing (feel free to post examples!)

Going to close the ticket since there aren't any immediate action items and to keep tickets to a minimum.  Feel free to continue the discussion here though.

**Comment by abhijitsarkar** [comment]
> what other projects are doing
All the projects I've come across use branching. I think that's the whole point of being on Github, otherwise any file server can manage directories.
