### ISSUE TITLE
Sync Gateway docker with ubuntu

### ISSUE THREAD

**Issue by gillez** [couchbase/docker#64]
Hi, 
I'm trying to build a docker image with sync_gateway using ubuntu as a base.  I'm getting the sync_gateway .deb package using wget then using "dpkg -i" to install this.  The deb package is ```http://packages.couchbase.com/releases/couchbase-sync-gateway/1.4.0/couchbase-sync-gateway-community_1.4.0-2_x86_64.deb```

The failure happens during the dpkg postinst configure phase, when it tries to perform the following:
```systemctl start sync_gateway```
This fails with the error ```Failed to connect to bus: No such file or directory```
Which then stops my whole build.

I've read [this](https://stackoverflow.com/questions/39169403/systemd-and-systemctl-within-ubuntu-docker-images) discussion of a similar failute (systemctl giving the same error in a docker container).  However, that relates to the error when running the docker container, not when building the image.

The official [Dockerfile](https://hub.docker.com/r/couchbase/sync-gateway/~/dockerfile/) for sync_gateway uses centos and that works.  However, I want to use ubuntu as I want to run my app and sync_gateway in the same container (actually using phusion/baseimage:0.9.22 as a base, which is a slightly modified ubuntu image.  Outside of docker, sync gateway works fine on Ubuntu.  

What is the reason that the sync_gateway Dockerfile uses centos rather than ubuntu (the Couchbase Server Dockerfile uses ubuntu)?  Is it because there is a known problem with the sync_gateway debian package in docker?  Can anyone please help with this? 

FYI, I've also posted this query in the Docker forums as I'm not sure if this is a sync_gateway or Docker issue.

Thanks,
Giles

**Comment by tleyden** [comment]
> This fails with the error Failed to connect to bus: No such file or directory

That's happening because `systemd` isn't running in the container, and it tries to start the sync_gateway systemd service for convenience reasons.   

Some ideas to get around that:

* `dpkg` might have a flag to prevent the `systemctl start sync_gateway` step from running (@ajres have you heard of that?)
* If there is a zip file download available for Sync Gateway, you could use that instead

> I want to use ubuntu as I want to run my app and sync_gateway in the same container

Just as a heads up, that approach is "frowned upon" by docker purists, who advocate basically running a single process in a container.  Having said that, I get that sometimes that it's not feasible given other constraints.

> What is the reason that the sync_gateway Dockerfile uses centos rather than ubuntu (the Couchbase Server Dockerfile uses ubuntu)?

I think it was just because most enterprise users gravitate towards RHEL and CentOS.

I'm going to close the issue until there are any action items, just to try to keep the issue tracker clean .. but feel free to continue the discussion here!

**Comment by tleyden** [comment]
Here is the .tar.gz version of a recent Sync Gateway version: http://latestbuilds.hq.couchbase.com/couchbase-sync-gateway/1.4.1/1.4.1-3/couchbase-sync-gateway-community_1.4.1-3_x86_64.tar.gz

**Comment by gillez** [comment]
Thanks Traun,

I'll try with this tgz file today.  

The explanation in the previous message made sense as well. On your point about preventing the systemctl cmd from running, I'm not sure if there's an option to do that, but I believe you can run "dpkg --unpack" rather than "--install" to just unpack the pkg file without configuring.  I guess this would be the same as (or very similar to) extracting the tgz file, so I can try this.

Regards,
Giles
