### ISSUE TITLE
Running couchbase as non root user

### ISSUE THREAD

**Issue by Zizou84** [couchbase/docker#75]
Hello,
I see you are creating a specific user (RUN groupadd -g 1000 couchbase && useradd couchbase -u 1000 -g couchbase -M) that could be mapped later to a user in the local machine but I didn't see the use of **USER** command to run as the created user.
Any explication please why not using the USER command?
Thanks

**Comment by ceejatec** [comment]
The Couchbase installer creates a "couchbase" user and runs all processes at that user. We do it in the Dockerfile before installing the .deb so we can ensure that this user gets userID 1000, which is necessary for instance on MacOS to ensure that bind-mounting /opt/couchbase/var doesn't hit permissions issues.

**Comment by Zizou84** [comment]
Thank ceejatec,
but shouldn't add a command "USER couchbase" before the ENTRYPOINT command to ensure running processes as couchbase?

**Comment by ceejatec** [comment]
No, the Couchbase Server startup scripts do that themselves. It's important that the ENTRYPOINT script is run as root so that it can modify the ownership of /opt/couchbase/var if necessary (on Linux platforms, it would otherwise fail unless the user doing "docker run" just happened to be user ID 1000).
