### ISSUE TITLE
Any plans to provide Alpine image?

### ISSUE THREAD

**Issue by Kitanotori** [couchbase/docker#76]
# Reason
- lightweight: 3.97MB (alpine:3.6) VS 122MB (ubuntu:16.04) VS 197MB (centos:7)
- community shift towards Alpine images: Docker team moved officially from Ubuntu to Alpine in 2016, and many others have followed since.

**Comment by ceejatec** [comment]
Extremely unlikely due to Alpine's use of a libc other than glibc. That would require at a minimum rebuilding a number of our third-party tools, which is a fair amount of work even assuming none of them have issues building in that environment. We would also need regular Alpine builds and testing. The space savings are only about 20% of our overall image size, so at the moment I don't see a justification for the effort. That could of course change if there is more demand from customers or the community.
